# Generated by Django 5.2.4 on 2025-10-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0016_alter_compasssample_deployment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='max_depth',
        ),
        migrations.AddField(
            model_name='mission',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('camera', 'Camera'), ('compass', 'Compass'), ('imu', 'IMU'), ('pressure', 'Pressure'), ('sonar', 'Sonar'), ('water_quality', 'Water Quality')], max_length=20),
        ),
    ]
