# Generated by Django 5.2.4 on 2025-10-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0017_remove_mission_max_depth_mission_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='max_depth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
