# Generated by Django 5.2.4 on 2025-10-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0018_mission_max_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='cloud_cover',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='tide_level',
        ),
        migrations.AddField(
            model_name='mission',
            name='driving_difficulty',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Driving difficulty: low, medium, or high', max_length=6),
        ),
    ]
