# Generated by Django 5.2.4 on 2025-10-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0019_remove_mission_cloud_cover_remove_mission_tide_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navsample',
            name='corrected_depth_m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
