# Generated by Django 5.2.4 on 2025-10-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0020_navsample_corrected_depth_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('image_set', 'ImageSet'), ('video', 'Video')], max_length=10),
        ),
    ]
