# Generated by Django 5.2.4 on 2025-11-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0021_alter_mediaasset_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TideLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(choices=[('ponta_delgada', 'Ponta Delgada'), ('horta', 'Horta')], default='ponta_delgada', max_length=20)),
                ('time', models.DateTimeField()),
                ('tide_height_m', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('image_set', 'Image Set'), ('video', 'Video')], max_length=10),
        ),
    ]
