# Generated by Django 5.2.4 on 2025-11-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0022_tidelevels_alter_mediaasset_media_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TideLevels',
            new_name='TideLevel',
        ),
    ]
