# Generated by Django 5.2.4 on 2025-11-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0023_rename_tidelevels_tidelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('camera', 'camera'), ('compass', 'Compass'), ('imu', 'IMU'), ('pressure', 'Pressure'), ('sonar', 'sonar'), ('water_quality', 'Water Quality')], max_length=20),
        ),
    ]
