# Generated by Django 5.2.4 on 2025-11-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0026_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameindex',
            name='servo_pitch_deg',
        ),
    ]
