# Generated by Django 5.2.4 on 2025-12-11 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0027_remove_frameindex_servo_pitch_deg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, help_text='Approximate latitude of the site', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Approximate longitude of the site', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='location_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='missions.location'),
        ),
    ]
