# Generated by Django 5.2.4 on 2025-12-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0028_location_mission_location_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='location',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='longitude',
        ),
    ]
