# Generated by Django 5.2.4 on 2025-12-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0029_remove_mission_latitude_remove_mission_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='location_link',
            new_name='location',
        ),
    ]
