# Generated by Django 5.2.4 on 2025-12-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0030_rename_location_link_mission_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='missions.location'),
        ),
    ]
