# Generated by Django 5.2.4 on 2025-12-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0031_alter_mission_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='generated_video_path',
            field=models.CharField(blank=True, help_text='Path to a video file generated from an image set', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
