# Generated by Django 5.2.4 on 2025-12-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0032_mediaasset_generated_video_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='max_depth_m',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='min_depth_m',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
